version: "3.4"
services:
  dev:
    image: bayesimpact/ma-voie-dev:${CIRCLE_BUILD_NUM:-latest}
    build:
      context: .
      target: dev
    command: npm start
    entrypoint: ./entrypoint.sh
    tty: true
    ports:
      - "9707:80"
  test:
    image: bayesimpact/ma-voie-test:${CIRCLE_BUILD_NUM:-latest}
    build:
      context: .
      args:
        - REACT_BASE_TAG
        - SKIP_TEST
      target: test
  nginx:
    image: bayesimpact/ma-voie:${CIRCLE_BUILD_NUM:-latest}
    build:
      context: .
      target: nginx
    ports:
      - 80
  server:
    image: bayesimpact/ma-voie-server:${CIRCLE_BUILD_NUM:-latest}
    build:
      context: .
      dockerfile: server/Dockerfile
      target: dev
    command: npm run serve
    entrypoint: ./entrypoint.sh
    environment:
      FIREBASE_TOKEN:
    ports:
      - "4000:4000"
      - "5000:5000"
  server-test:
    image: bayesimpact/ma-voie-server-test:${CIRCLE_BUILD_NUM:-latest}
    build:
      context: .
      dockerfile: server/Dockerfile
      target: test
