# Overrides of Compose services used to help develop faster without rebuilding
# the container on every change.
version: "3.4"
services:
  dev:
    volumes:
      - ./cfg:/usr/app/cfg
      - ./ssl:/etc/ssl/webpack-dev:ro
      - ./.babelrc:/usr/app/.babelrc:ro
      - ./src:/usr/app/src
      - ./check-color-config.sh:/usr/app/check-color-config.sh:ro
      - ./custom.d.ts:/usr/app/custom.d.ts:ro
      - ./diff_i18n_folder.sh:/usr/app/diff_i18n_folder.sh:ro
      - ./jsonlint.sh:/usr/app/jsonlint.sh
      - ./entrypoint.sh:/usr/app/entrypoint.sh:ro
      - ./package.json:/usr/app/package.json:ro
      - ./tsconfig.json:/usr/app/tsconfig.json:ro
      # For linting.
      - ./.eslintrc.json:/usr/app/.eslintrc.json:ro
      - ./.eslintignore:/usr/app/.eslintignore:ro
      # For testing.
      - ./test:/usr/app/test
      - ./karma.conf.js:/usr/app/karma.conf.js:ro
      # For translation.
      - ./i18n.babelrc.js:/usr/app/i18n.babelrc.js:ro
      # For releasing.
      - ./dist:/usr/app/dist
      # TODO(pascal): Create a @types/autocomplete.js npm package.
      - ./vendor/autocomplete.js.d.ts:/usr/app/node_modules/@types/autocomplete.js/index.d.ts
    environment:
      TUNNEL_TESTING:
      CLIENT_VERSION: dev
  server:
    environment:
      FIREBASE_TOKEN:
    volumes:
      - ./server/package.json:/usr/app/package.json
      - ./.eslintrc.json:/usr/app/.eslintrc.json
      - ./.eslintignore:/usr/app/.eslintignore
      - ./server/.firebaserc:/usr/app/.firebaserc
      - ./server/entrypoint.sh:/usr/app/entrypoint.sh
      - ./server/firebase.json:/usr/app/firebase.json
      - ./server/tsconfig.json:/usr/app/tsconfig.json
      - ./server/src:/usr/app/src
